[package]
name = "mmux-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true }
buffa = { workspace = true }
clap = { workspace = true }
connectrpc = { workspace = true }
http = { workspace = true }
mmux-shared = { path = "../mmux-shared" }
mmux-wire = { path = "../mmux-wire" }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
webpki-roots = { workspace = true }

[features]
default = []
