[microsandbox.runtime]
image = "debian:bookworm-slim"
memory_mib = 4096
cpus = 2

[microsandbox.assets]
mmux_version = "v0.1.0"
scripts_dir = "./mmux_sources/scripts"
assets_dir = "./mmux_sources/assets"
