[microsandbox.runtime]
image = "debian:bookworm-slim"
# memory_mib = 1024
# cpus = 2

[microsandbox.assets]
mmux_source = { repo = "https://github.com/ilijaljubicic/mmux.git", ref = "main" }
scripts_dir = "./mmux_sources/scripts"
assets_dir = "./mmux_sources/assets"
